import React, { useState, useEffect, useRef } from "react";
import { useStore } from "../stores/useStore";

export default function CanvasEditor() {
  const { uploadedImageBase64, selectedProducts, analysis, removeProduct, addProduct, allProducts } = useStore();
  const [composedImage, setComposedImage] = useState<string | null>(null);
  const [scenePrompt, setScenePrompt] = useState("");
  const [generating, setGenerating] = useState(false);
  const [chatInput, setChatInput] = useState("");
  const [chatMessages, setChatMessages] = useState<{role: string; text: string}[]>([]);
  const [showProducts, setShowProducts] = useState(true);
  const hasAutoGenerated = useRef(false);

  // Auto-generate once on first load (ref prevents React StrictMode double-fire)
  useEffect(() => {
    if (hasAutoGenerated.current) return;
    if (selectedProducts.length > 0 && !composedImage && !generating) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
  }, []);

  const handleGenerate = async () => {
    if (selectedProducts.length === 0) return;
    setGenerating(true);
    setChatMessages(prev => [...prev, { role: "system", text: `正在生成场景图（${selectedProducts.length}件商品）...` }]);

    try {
      const resp = await fetch("/api/compose", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          roomImageBase64: uploadedImageBase64,
          selectedProducts,
          analysis,
        }),
      });
      const data = await resp.json();

      if (data.success) {
        setComposedImage(data.composedImage);
        setScenePrompt(data.scenePrompt);
        setChatMessages(prev => [...prev, { role: "ai", text: "场景生成完成！你可以告诉我需要什么调整。" }]);
      } else {
        setChatMessages(prev => [...prev, { role: "ai", text: `生成失败: ${data.error}` }]);
      }
    } catch (err: any) {
      setChatMessages(prev => [...prev, { role: "ai", text: `出错: ${err.message}` }]);
    } finally {
      setGenerating(false);
    }
  };

  const handleAdjust = async () => {
    if (!chatInput.trim() || generating) return;
    const feedback = chatInput.trim();
    setChatInput("");
    setChatMessages(prev => [...prev, { role: "user", text: feedback }]);
    setGenerating(true);

    try {
      const resp = await fetch("/api/compose/adjust", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          previousPrompt: scenePrompt,
          userFeedback: feedback,
          selectedProducts,
          analysis,
        }),
      });
      const data = await resp.json();

      if (data.success) {
        setComposedImage(data.composedImage);
        setScenePrompt(data.scenePrompt);
        setChatMessages(prev => [...prev, { role: "ai", text: data.message || "已重新生成" }]);
      } else {
        setChatMessages(prev => [...prev, { role: "ai", text: `调整失败: ${data.error}` }]);
      }
    } catch (err: any) {
      setChatMessages(prev => [...prev, { role: "ai", text: `出错: ${err.message}` }]);
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = () => {
    if (!composedImage) return;
    const link = document.createElement("a");
    link.download = `softdecor-scene-${Date.now()}.png`;
    link.href = composedImage;
    link.click();
  };

  const availableProducts = allProducts.filter(
    (p) => !selectedProducts.some((sp) => sp.sku === p.sku)
  );

  return (
    <div className="flex gap-6">
      {/* Main area - Scene */}
      <div className="flex-1 min-w-0">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-xl font-bold text-slate-800">AI 场景合成</h2>
          <div className="flex gap-2">
            <button onClick={handleGenerate} disabled={generating || selectedProducts.length === 0}
              className="px-4 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors">
              {generating ? "生成中..." : composedImage ? "重新生成" : "生成场景"}
            </button>
            {composedImage && (
              <button onClick={handleDownload}
                className="px-4 py-2 text-sm border border-slate-300 rounded-lg hover:bg-slate-50 transition-colors">
                下载
              </button>
            )}
          </div>
        </div>

        {/* Scene display */}
        <div className="bg-slate-100 rounded-2xl overflow-hidden border border-slate-200 min-h-[500px] flex items-center justify-center">
          {generating && !composedImage && (
            <div className="text-center py-20">
              <div className="w-16 h-16 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
              <p className="text-slate-600 font-medium">AI 正在生成场景图...</p>
              <p className="text-slate-400 text-sm mt-1">Opus 分析 → Seedream 生图，约15-20秒</p>
            </div>
          )}
          {composedImage && (
            <div className="relative w-full">
              <img src={composedImage} alt="AI Generated Scene" className="w-full rounded-2xl" />
              {generating && (
                <div className="absolute inset-0 bg-black/30 rounded-2xl flex items-center justify-center">
                  <div className="bg-white rounded-xl px-6 py-3 flex items-center gap-3 shadow-lg">
                    <div className="w-5 h-5 border-2 border-blue-500 border-t-transparent rounded-full animate-spin" />
                    <span>重新生成中...</span>
                  </div>
                </div>
              )}
            </div>
          )}
          {!generating && !composedImage && (
            <div className="text-center py-20">
              <p className="text-slate-400 text-lg">选择商品后点击"生成场景"</p>
            </div>
          )}
        </div>
      </div>

      {/* Sidebar */}
      <div className="w-80 flex flex-col gap-4 max-h-[750px]">
        {/* AI Chat */}
        <div className="border border-slate-200 rounded-xl p-3 bg-slate-50">
          <h3 className="font-semibold text-slate-700 text-sm mb-2">AI 设计助手</h3>
          <div className="h-40 overflow-y-auto mb-2 space-y-1.5 text-xs">
            {chatMessages.length === 0 && (
              <p className="text-slate-400 italic">生成场景后，可以告诉AI如何调整，例如：<br/>"沙发换成深色的" "加一盏落地灯" "整体氛围再温馨一些"</p>
            )}
            {chatMessages.map((m, i) => (
              <div key={i} className={`px-2.5 py-1.5 rounded-lg ${
                m.role === "user" ? "bg-blue-100 text-blue-800 ml-6" :
                m.role === "system" ? "bg-yellow-50 text-yellow-700 text-center italic" :
                "bg-white text-slate-700 mr-4 border border-slate-200"
              }`}>
                {m.text}
              </div>
            ))}
          </div>
          <div className="flex gap-1.5">
            <input
              value={chatInput}
              onChange={e => setChatInput(e.target.value)}
              onKeyDown={e => e.key === "Enter" && handleAdjust()}
              placeholder="描述你想要的调整..."
              disabled={generating || !composedImage}
              className="flex-1 px-3 py-1.5 text-sm border border-slate-300 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-400 disabled:bg-slate-100"
            />
            <button onClick={handleAdjust} disabled={generating || !composedImage || !chatInput.trim()}
              className="px-3 py-1.5 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50">
              发送
            </button>
          </div>
        </div>

        {/* Selected Products */}
        <div className="overflow-y-auto flex-1 border border-slate-200 rounded-xl p-3">
          <div className="flex items-center justify-between mb-2">
            <h3 className="font-semibold text-slate-700 text-sm">
              已选商品 ({selectedProducts.length})
            </h3>
            <span className="text-xs text-slate-400">
              ¥{selectedProducts.reduce((s, p) => s + p.price, 0).toLocaleString()}
            </span>
          </div>

          {selectedProducts.map((p) => (
            <div key={p.sku} className="flex items-center gap-2 p-1.5 rounded-lg mb-1.5 bg-blue-50 border border-blue-200">
              <img src={p.img} alt={p.name} className="w-10 h-10 rounded object-contain bg-white" crossOrigin="anonymous" />
              <div className="flex-1 min-w-0">
                <p className="text-xs font-medium text-slate-800 truncate">{p.name}</p>
                <p className="text-xs text-slate-400">{p.cat} · {p.style} · ¥{p.price}</p>
              </div>
              <button onClick={() => removeProduct(p.sku)} className="text-red-400 hover:text-red-600 p-0.5">
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          ))}

          <button onClick={() => setShowProducts(!showProducts)}
            className="w-full text-xs text-blue-600 mt-3 py-1 hover:underline">
            {showProducts ? "收起更多商品" : "展开添加更多商品"}
          </button>

          {showProducts && availableProducts.length > 0 && (
            <div className="mt-2 space-y-1">
              {availableProducts.map((p) => (
                <div key={p.sku}
                  className="flex items-center gap-2 p-1.5 rounded-lg hover:bg-slate-50 cursor-pointer border border-slate-100"
                  onClick={() => addProduct(p)}>
                  <img src={p.img} alt={p.name} className="w-8 h-8 rounded object-contain bg-white" crossOrigin="anonymous" />
                  <div className="flex-1 min-w-0">
                    <p className="text-xs text-slate-700 truncate">{p.name}</p>
                    <p className="text-xs text-slate-400">{p.style} ¥{p.price}</p>
                  </div>
                  <span className="text-blue-500 text-sm">+</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
